package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

// Config holds user-configurable settings for the tacit pipeline.
// Loaded by merging ~/.tacit/config.yaml (setup-managed defaults) and
// ~/.tacit/config-override.yaml (user overrides). Missing files mean
// all Go defaults apply.
type Config struct {
	WhisperModel    string        `yaml:"whisper_model"`
	InitialPrompt   string        `yaml:"initial_prompt"`
	MinSpeechDur    time.Duration `yaml:"min_speech_duration"`
	SilenceDuration time.Duration `yaml:"silence_duration"`
	SpeechThreshold float64       `yaml:"speech_threshold"`
	EnergyThreshold float64       `yaml:"energy_threshold"`
	LLMProvider     string        `yaml:"llm_provider"`
	LLMModel        string        `yaml:"llm_model"`
}

// DefaultConfig returns a Config populated with default values.
func DefaultConfig() *Config {
	return &Config{
		WhisperModel:    "medium",
		MinSpeechDur:    8 * time.Second,
		SilenceDuration: 1500 * time.Millisecond,
		SpeechThreshold: 0.5,
		EnergyThreshold: 200,
		LLMProvider:     "ollama",
		LLMModel:        "qwen3.5",
	}
}

// loadFile reads a YAML file at path and unmarshals it into cfg.
// If the file does not exist, it returns nil without modifying cfg.
func loadFile(path string, cfg *Config) error {
	data, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	return yaml.Unmarshal(data, cfg)
}

// LoadWithOverride merges configuration from two YAML files into a single Config.
// Load order: DefaultConfig() → configPath → overridePath.
// Either path may be empty or nonexistent; missing files are silently skipped.
func LoadWithOverride(configPath, overridePath string) (*Config, error) {
	cfg := DefaultConfig()
	if configPath != "" {
		if err := loadFile(configPath, cfg); err != nil {
			return nil, fmt.Errorf("loading %s: %w", configPath, err)
		}
	}
	if overridePath != "" {
		if err := loadFile(overridePath, cfg); err != nil {
			return nil, fmt.Errorf("loading %s: %w", overridePath, err)
		}
	}
	return cfg, nil
}

// LoadOverrideKeys returns the set of YAML keys explicitly present in the
// override file at overridePath. If the file does not exist, an empty map is
// returned without error.
func LoadOverrideKeys(overridePath string) (map[string]bool, error) {
	data, err := os.ReadFile(overridePath)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return map[string]bool{}, nil
		}
		return nil, err
	}
	raw := map[string]interface{}{}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	keys := make(map[string]bool, len(raw))
	for k := range raw {
		keys[k] = true
	}
	return keys, nil
}

// WriteDefault writes a reference config.yaml to path with a header comment
// that explains it is setup-managed and should not be edited by users.
// Duration fields are formatted as human-readable strings (e.g. "8s", "1.5s").
func WriteDefault(path string) error {
	cfg := DefaultConfig()
	content := fmt.Sprintf(
		"# tacit reference config — DO NOT EDIT.\n"+
			"# This file is regenerated by 'tacit setup' and documents available fields.\n"+
			"# To override values, edit config-override.yaml in the same directory.\n\n"+
			"whisper_model: %s\n"+
			"initial_prompt: \"\"\n"+
			"min_speech_duration: %s\n"+
			"silence_duration: %s\n"+
			"speech_threshold: %.2f\n"+
			"energy_threshold: %.0f\n"+
			"llm_provider: %s\n"+
			"llm_model: %s\n",
		cfg.WhisperModel,
		formatDuration(cfg.MinSpeechDur),
		formatDuration(cfg.SilenceDuration),
		cfg.SpeechThreshold,
		cfg.EnergyThreshold,
		cfg.LLMProvider,
		cfg.LLMModel,
	)
	return os.WriteFile(path, []byte(content), 0644)
}

// WriteOverrideTemplate creates a config-override.yaml template at path with
// all fields commented out. Users uncomment and set only the fields they want
// to override. The template values reflect the current defaults.
func WriteOverrideTemplate(path string, defaults *Config) error {
	header := "# tacit user overrides — edit this file to customize tacit.\n" +
		"# Only fields you uncomment and set here will override the defaults.\n" +
		"# Run 'tacit config view' to see the current merged configuration.\n\n"

	fields := []string{
		fmt.Sprintf("whisper_model: %s", defaults.WhisperModel),
		fmt.Sprintf("initial_prompt: \"\""),
		fmt.Sprintf("min_speech_duration: %s", formatDuration(defaults.MinSpeechDur)),
		fmt.Sprintf("silence_duration: %s", formatDuration(defaults.SilenceDuration)),
		fmt.Sprintf("speech_threshold: %.2f", defaults.SpeechThreshold),
		fmt.Sprintf("energy_threshold: %.0f", defaults.EnergyThreshold),
		fmt.Sprintf("llm_provider: %s", defaults.LLMProvider),
		fmt.Sprintf("llm_model: %s", defaults.LLMModel),
	}

	var sb strings.Builder
	sb.WriteString(header)
	for _, f := range fields {
		sb.WriteString("# ")
		sb.WriteString(f)
		sb.WriteByte('\n')
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}

// formatDuration formats a time.Duration as a human-readable string.
func formatDuration(d time.Duration) string {
	if d == 0 {
		return "0s"
	}
	if d%time.Second == 0 {
		return fmt.Sprintf("%ds", int(d.Seconds()))
	}
	// Show as decimal seconds for sub-second or fractional values (e.g. "1.5s").
	return fmt.Sprintf("%.4gs", d.Seconds())
}

// BaseDir returns the root directory for the tacit knowledge base (~/.tacit).
func BaseDir() string {
	home, err := os.UserHomeDir()
	if err != nil {
		// Fallback: this should not happen on supported platforms.
		return filepath.Join(os.Getenv("HOME"), ".tacit")
	}
	return filepath.Join(home, ".tacit")
}

// ConfigPath returns the default config file path (~/.tacit/config.yaml).
func ConfigPath() string {
	return filepath.Join(BaseDir(), "config.yaml")
}

// OverridePath returns the user override config file path (~/.tacit/config-override.yaml).
func OverridePath() string {
	return filepath.Join(BaseDir(), "config-override.yaml")
}

// ModelPath returns the path for a whisper model file (~/.tacit/models/ggml-{model}.bin).
func ModelPath(model string) string {
	return filepath.Join(BaseDir(), "models", "ggml-"+model+".bin")
}

// PIDPath returns the path for the daemon PID file (~/.tacit/tacit.pid).
func PIDPath() string {
	return filepath.Join(BaseDir(), "tacit.pid")
}

// WriteSetupOverride writes a full override template with llm_provider and
// llm_model set to the given values (uncommented). Other fields are preserved
// from the existing override file if present; otherwise they remain commented
// out with their default values so users can easily edit them later.
func WriteSetupOverride(path string, provider, model string) error {
	// Load existing override values to preserve non-LLM user settings.
	existing := map[string]interface{}{}
	if data, err := os.ReadFile(path); err == nil {
		_ = yaml.Unmarshal(data, &existing)
	}

	defaults := DefaultConfig()

	header := "# tacit user overrides — edit this file to customize tacit.\n" +
		"# Only fields you uncomment and set here will override the defaults.\n" +
		"# Run 'tacit config view' to see the current merged configuration.\n\n"

	type field struct {
		key        string
		value      string
		forceActive bool // true = always write uncommented
	}

	fields := []field{
		{"whisper_model", defaults.WhisperModel, false},
		{"initial_prompt", "\"\"", false},
		{"min_speech_duration", formatDuration(defaults.MinSpeechDur), false},
		{"silence_duration", formatDuration(defaults.SilenceDuration), false},
		{"speech_threshold", fmt.Sprintf("%.2f", defaults.SpeechThreshold), false},
		{"energy_threshold", fmt.Sprintf("%.0f", defaults.EnergyThreshold), false},
		{"llm_provider", provider, true},
		{"llm_model", model, true},
	}

	var sb strings.Builder
	sb.WriteString(header)
	for _, f := range fields {
		active := f.forceActive || existing[f.key] != nil
		if active {
			sb.WriteString(f.key + ": " + f.value + "\n")
		} else {
			sb.WriteString("# " + f.key + ": " + f.value + "\n")
		}
	}

	return os.WriteFile(path, []byte(sb.String()), 0644)
}
